version: 'build-{build}'

image: Visual Studio 2017

configuration:
- Release

platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- cmd: git config --global core.autocrlf true
- ps: $Env:NUGET_VERSION = "1.0.0-preview1-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(nuget_version)
  package_version: $(nuget_version)

before_build:
- appveyor-retry dotnet restore -v Minimal

build:
 project: SourceCode.Chasm.sln
 verbosity: minimal

test_script:
- ps: .\GenerateTestSolution.ps1 .\SourceCode.Chasm.sln
- >-
    OpenCover.Console.exe 
    -target:"dotnet.exe" 
    -targetargs:"test SourceCode.Chasm.Tests.sln -c %CONFIGURATION% --no-build" 
    -filter:"+[SourceCode.*]* -[*.Tests]*" 
    -output:"$(appveyor_build_folder)\coverage.xml" 
    -excludebyattribute:*.ExcludeFromCodeCoverage* 
    -oldStyle 
    -register:user 
    -mergebyhash 
    -hideskipped:File

after_test:
- pip install codecov 
- codecov -X gcov -f "$(appveyor_build_folder)\coverage.xml"

artifacts:
  - path: '**\*.nupkg'
  - path: 'coverage.xml'

deploy:
  provider: NuGet
  api_key:
    secure: JlUgeUsCDsMvMo4u5DwopSnGM4+FByY6kc0WQw841Bt0BX7ntT09kiH2R6ybWAOO
  on:
    branch: master
    is_not_pr: true
