version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "preview1-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\SourceCode.Chasm\SourceCode.Chasm.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\SourceCode.Chasm.Tests\SourceCode.Chasm.Tests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

- dotnet build "src\SourceCode.Chasm.IO.Json\SourceCode.Chasm.IO.Json.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\SourceCode.Chasm.IO.Json.Tests\SourceCode.Chasm.IO.Json.Tests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

- dotnet build "src\SourceCode.Chasm.IO.Bond\SourceCode.Chasm.IO.Bond.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\SourceCode.Chasm.IO.Bond.Tests\SourceCode.Chasm.IO.Bond.Tests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

- dotnet build "src\SourceCode.Chasm.IO.Proto\SourceCode.Chasm.IO.Proto.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\SourceCode.Chasm.IO.Proto.Tests\SourceCode.Chasm.IO.Proto.Tests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
 - dotnet pack "src\SourceCode.Chasm\SourceCode.Chasm.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
 - dotnet pack "src\SourceCode.Chasm.IO.Json\SourceCode.Chasm.IO.Json.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
 - dotnet pack "src\SourceCode.Chasm.IO.Bond\SourceCode.Chasm.IO.Bond.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
 - dotnet pack "src\SourceCode.Chasm.IO.Proto\SourceCode.Chasm.IO.Proto.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%

test_script:
- OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test src\SourceCode.Chasm.Tests\SourceCode.Chasm.Tests.csproj -c %CONFIGURATION% --no-build" -filter:"+[SourceCode.Chasm*]* -[SourceCode.Chasm.IO.Bond.Tests*]* -[SourceCode.Chasm.IO.Json.Tests*]* -[SourceCode.Chasm.IO.Proto.Tests*]* -[SourceCode.Chasm.Tests*]*" -output:"C:\projects\chasm\sourcecode-chasm.xml" -excludebyattribute:*.ExcludeFromCodeCoverage* -oldStyle -register:user -mergebyhash -hideskipped:File

#- dotnet test "src\SourceCode.Chasm.Tests\SourceCode.Chasm.Tests.csproj" -c %CONFIGURATION% --no-build
#- dotnet test "src\SourceCode.Chasm.IO.Json.Tests\SourceCode.Chasm.IO.Json.Tests.csproj" -c %CONFIGURATION% --no-build
#- dotnet test "src\SourceCode.Chasm.IO.Bond.Tests\SourceCode.Chasm.IO.Bond.Tests.csproj" -c %CONFIGURATION% --no-build
#- dotnet test "src\SourceCode.Chasm.IO.Proto.Tests\SourceCode.Chasm.IO.Proto.Tests.csproj" -c %CONFIGURATION% --no-build

artifacts:
  - path: '**\*.nupkg'
#deploy:
#  provider: NuGet
#  api_key:
#    secure: JlUgeUsCDsMvMo4u5DwopSnGM4+FByY6kc0WQw841Bt0BX7ntT09kiH2R6ybWAOO
# on:
#    branch: master
#    is_not_pr: true
